# HTTP推送：外部程序调用云崽接口发送消息
# 是否启用推送
enable: false
# 用哪个协议端发送，留空自动选择
bot: ""
# 推送地址，示例：localhost:3000，留空使用云崽服务器地址，修改后需要重启云崽
baseUrl: ""
# 推送地址后缀，留空表示直接挂载到推送地址路径，修改后需要重启云崽
path: "/push"
# 访问 Token 留空表示不校验
token: ""
# 是否允许浏览器跨域调用
cors: true
# 是否在推送消息开头添加收到请求的时间
addReceiveTime: false
# 推送消息格式，array 为消息段，string 为 CQ 码
messageFormat: "array"
# 推送消息关键词拦截，命中后返回成功但不发送，支持 \n 换行和 {at:*} 艾特条件
block: []
# 推送消息关键词替换，触发条件、排除条件和被替换内容可多选，to 为空表示删除，支持 \n 换行和 {at:目标ID} 艾特，{at:*} 可匹配任意真实艾特
replace: []
# 群聊推送命中关键词时，在消息开头艾特指定QQ
at: []
